apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-angular
  description: Angular frontend for backstage testing
  annotations:
    github.com/project-slug: sairam3333/backstage-angular
spec:
  type: website
  lifecycle: production
  owner: elite-frontend-team